# Generated by Django 4.2.27 on 2025-12-16 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('common_causes', models.TextField()),
                ('fix_instructions', models.TextField(help_text='Step-by-step instructions to fix')),
                ('machine_adjustments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_number', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='master_samples/')),
                ('description', models.TextField(blank=True)),
                ('specifications', models.TextField(help_text='Key specifications and tolerances')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mould',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mould_number', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cavity_count', models.IntegerField(default=1)),
                ('material_type', models.CharField(max_length=100)),
                ('cycle_time', models.FloatField(help_text='Cycle time in seconds')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TroubleshootingIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('quality', 'Quality Issue'), ('machine', 'Machine Issue'), ('material', 'Material Issue'), ('mould', 'Mould Issue'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('symptoms', models.TextField(help_text='Observable symptoms')),
                ('solution', models.TextField(help_text='Step-by-step solution')),
                ('prevention', models.TextField(blank=True, help_text='How to prevent this issue')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TroubleshootingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_number', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('resolution', models.TextField(blank=True)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moulding.troubleshootingissue')),
                ('mould', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moulding.mould')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='product_comparisons/')),
                ('machine_number', models.CharField(max_length=50)),
                ('similarity_score', models.FloatField(blank=True, help_text='0-100 similarity percentage', null=True)),
                ('defects_found', models.BooleanField(default=False)),
                ('defect_description', models.TextField(blank=True)),
                ('fix_instructions', models.TextField(blank=True)),
                ('approved', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('master_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moulding.mastersample')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MouldChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('scheduled_time', models.DateTimeField()),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mould_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changes_from', to='moulding.mould')),
                ('mould_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes_to', to='moulding.mould')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mastersample',
            name='mould',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moulding.mould'),
        ),
        migrations.CreateModel(
            name='HourlyChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_number', models.CharField(max_length=50)),
                ('check_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('visual_inspection', models.BooleanField(default=False)),
                ('dimensional_check', models.BooleanField(default=False)),
                ('color_consistency', models.BooleanField(default=False)),
                ('surface_finish', models.BooleanField(default=False)),
                ('temperature_ok', models.BooleanField(default=False)),
                ('pressure_ok', models.BooleanField(default=False)),
                ('cycle_time_ok', models.BooleanField(default=False)),
                ('material_level_ok', models.BooleanField(default=False)),
                ('material_drying_ok', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('issues_found', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mould', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moulding.mould')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
