# Generated by Django 5.2.6 on 2025-12-31 16:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moulding', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MouldRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_number', models.CharField(max_length=50)),
                ('setter_name', models.CharField(help_text='Name of the setter', max_length=200)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('setter_completion_time', models.DateTimeField(help_text='When setter completed the setup')),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mould', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moulding.mould')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
    ]
