# Generated by Django 5.2.6 on 2026-01-05 09:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moulding', '0003_company_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100, unique=True)),
                ('product_name', models.CharField(max_length=200)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_contact', models.CharField(blank=True, max_length=100)),
                ('quantity_ordered', models.IntegerField(help_text='Total quantity to produce')),
                ('quantity_produced', models.IntegerField(default=0, help_text='Quantity already produced')),
                ('unit', models.CharField(default='pieces', help_text='Unit of measurement', max_length=50)),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('special_requirements', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mould', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_orders', to='moulding.mould')),
            ],
            options={
                'ordering': ['-priority', 'due_date', '-created_at'],
            },
        ),
    ]
