# Generated by Django 5.2.6 on 2026-01-05 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moulding', '0005_issuecategory_issue_issuecomment_maintenancejobcard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HousekeepingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('area_type', models.CharField(choices=[('machine', 'Machine'), ('mould', 'Mould'), ('factory_floor', 'Factory Floor'), ('storage', 'Storage Area'), ('workstation', 'Workstation'), ('other', 'Other')], max_length=20)),
                ('area_description', models.CharField(help_text='e.g., Machine #5, Mould Storage, Production Floor', max_length=200)),
                ('before_image', models.ImageField(blank=True, null=True, upload_to='housekeeping/before/')),
                ('before_notes', models.TextField(blank=True, help_text='Condition before cleaning')),
                ('after_image', models.ImageField(blank=True, null=True, upload_to='housekeeping/after/')),
                ('after_notes', models.TextField(blank=True, help_text='Condition after cleaning')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cleaning_products_used', models.TextField(blank=True, help_text='List of cleaning products used')),
                ('issues_found', models.TextField(blank=True, help_text='Any issues discovered during cleaning')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housekeeping_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
