# Generated by Django 5.2.6 on 2026-02-14 00:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moulding', '0006_housekeepingtask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Masterbatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g., MB-RED-001, MB-BLK-002', max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('color', 'Color Masterbatch'), ('additive', 'Additive Masterbatch'), ('filler', 'Filler Masterbatch'), ('uv', 'UV Stabilizer'), ('flame', 'Flame Retardant')], default='color', max_length=20)),
                ('color_name', models.CharField(blank=True, help_text='e.g., Red, Blue, Black', max_length=100)),
                ('color_code', models.CharField(blank=True, help_text='Pantone or RAL code', max_length=50)),
                ('hex_color', models.CharField(blank=True, help_text='#RRGGBB', max_length=7)),
                ('supplier', models.CharField(max_length=200)),
                ('supplier_code', models.CharField(blank=True, max_length=100)),
                ('recommended_dosage', models.FloatField(help_text='% in final product')),
                ('min_dosage', models.FloatField(blank=True, help_text='% minimum', null=True)),
                ('max_dosage', models.FloatField(blank=True, help_text='% maximum', null=True)),
                ('compatible_materials', models.TextField(blank=True, help_text='e.g., PP, PE, ABS')),
                ('current_stock', models.FloatField(default=0, help_text='kg')),
                ('minimum_stock', models.FloatField(default=0, help_text='kg')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('carrier_resin', models.CharField(blank=True, help_text='e.g., PP, PE', max_length=100)),
                ('pigment_content', models.FloatField(blank=True, help_text='% pigment', null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['type', 'color_name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g., PP-V-001, ABS-R-002', max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('virgin', 'Virgin Material'), ('regrind', 'Regrind Material'), ('mixed', 'Mixed (Virgin + Regrind)')], max_length=20)),
                ('material_grade', models.CharField(help_text='e.g., PP, ABS, PE, PVC, Nylon', max_length=100)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('density', models.FloatField(blank=True, help_text='g/cm³', null=True)),
                ('melt_flow_index', models.FloatField(blank=True, help_text='MFI g/10min', null=True)),
                ('moisture_content', models.FloatField(blank=True, help_text='% max', null=True)),
                ('regrind_percentage', models.IntegerField(default=0, help_text='% if mixed with virgin')),
                ('source', models.CharField(blank=True, help_text='Source of regrind', max_length=200)),
                ('current_stock', models.FloatField(default=0, help_text='kg')),
                ('minimum_stock', models.FloatField(default=0, help_text='kg')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('drying_temperature', models.IntegerField(blank=True, help_text='°C', null=True)),
                ('drying_time', models.IntegerField(blank=True, help_text='hours', null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='MaterialRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=200)),
                ('base_percentage', models.FloatField(help_text='% of base material')),
                ('masterbatch_percentage', models.FloatField(default=0, help_text='% of masterbatch')),
                ('regrind_percentage', models.FloatField(default=0, help_text='% of regrind')),
                ('total_weight_per_part', models.FloatField(blank=True, help_text='grams per part', null=True)),
                ('color_specification', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('masterbatch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='moulding.masterbatch')),
                ('mould', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moulding.mould')),
                ('base_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='moulding.materialtype')),
                ('regrind_material', models.ForeignKey(blank=True, limit_choices_to={'category': 'regrind'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regrind_recipes', to='moulding.materialtype')),
            ],
            options={
                'ordering': ['recipe_code'],
            },
        ),
        migrations.CreateModel(
            name='MaterialUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('machine_number', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=200)),
                ('material_quantity', models.FloatField(help_text='kg used')),
                ('masterbatch_quantity', models.FloatField(default=0, help_text='kg used')),
                ('masterbatch_percentage', models.FloatField(default=0, help_text='% in mix')),
                ('additional_regrind', models.FloatField(default=0, help_text='kg additional regrind')),
                ('regrind_percentage', models.FloatField(default=0, help_text='% regrind in total mix')),
                ('parts_produced', models.IntegerField(default=0)),
                ('good_parts', models.IntegerField(default=0)),
                ('rejected_parts', models.IntegerField(default=0)),
                ('material_per_part', models.FloatField(default=0, help_text='kg per part')),
                ('scrap_rate', models.FloatField(default=0, help_text='% scrap')),
                ('shift', models.CharField(blank=True, help_text='e.g., Day, Night, Morning', max_length=20)),
                ('production_date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('masterbatch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usages', to='moulding.masterbatch')),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='moulding.materialtype')),
                ('mould', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moulding.mould')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-production_date', '-start_time'],
            },
        ),
    ]
