# Generated by Django 5.2.6 on 2026-03-04 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moulding', '0007_masterbatch_materialtype_materialrecipe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='base_material_required',
            field=models.FloatField(default=0, help_text='kg of base material needed'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='estimated_material_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='masterbatch_required',
            field=models.FloatField(default=0, help_text='kg of masterbatch needed'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='material_recipe',
            field=models.ForeignKey(blank=True, help_text='Material recipe for this product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders', to='moulding.materialrecipe'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='regrind_required',
            field=models.FloatField(default=0, help_text='kg of regrind needed'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='total_material_required',
            field=models.FloatField(default=0, help_text='Total kg needed'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='weight_per_part',
            field=models.FloatField(blank=True, help_text='grams per part', null=True),
        ),
    ]
