# Generated by Django 5.2.6 on 2026-03-05 17:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moulding', '0008_productionorder_base_material_required_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('shift', models.CharField(choices=[('day', 'Day Shift'), ('night', 'Night Shift'), ('morning', 'Morning Shift'), ('afternoon', 'Afternoon Shift'), ('evening', 'Evening Shift')], max_length=20)),
                ('shift_date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.TimeField(help_text='Shift start time')),
                ('end_time', models.TimeField(help_text='Shift end time')),
                ('quantity_produced', models.IntegerField(help_text='Good parts produced this shift')),
                ('quantity_rejected', models.IntegerField(default=0, help_text='Rejected parts this shift')),
                ('total_quantity', models.IntegerField(default=0, help_text='Total parts attempted')),
                ('scrap_rate', models.FloatField(default=0, help_text='% scrap rate')),
                ('production_rate', models.FloatField(default=0, help_text='Parts per hour')),
                ('machine_number', models.CharField(max_length=50)),
                ('supervisor', models.CharField(blank=True, help_text='Supervisor name', max_length=200)),
                ('downtime_minutes', models.IntegerField(default=0, help_text='Minutes of downtime')),
                ('downtime_reason', models.TextField(blank=True, help_text='Reason for downtime')),
                ('material_used', models.FloatField(blank=True, default=0, help_text='kg of material used')),
                ('notes', models.TextField(blank=True, help_text='Shift notes, issues, observations')),
                ('quality_issues', models.TextField(blank=True, help_text='Any quality issues encountered')),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_shift_productions', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_productions', to=settings.AUTH_USER_MODEL)),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_productions', to='moulding.productionorder')),
            ],
            options={
                'ordering': ['-shift_date', '-start_time'],
                'unique_together': {('production_order', 'shift', 'shift_date')},
            },
        ),
    ]
